"""Added salt table

Revision ID: 5c0f27e7a00e
Revises: b5aa78f378e0
Create Date: 2018-03-26 14:39:14.521205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0f27e7a00e'
down_revision = 'b5aa78f378e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salts')
    # ### end Alembic commands ###
